pipeline {
   stages {
        stage("Git Checkout"){
           steps {
               git cfredentialsId: 'github', url: 'https://github.com/vijayalaxmiduvva/mvnproject.git'
           }
        }
   }
} 
