 // comment
 pipeline {
  agent any  
  stages {
        stage('Checkout git'){
           steps{
            git pull: true, url: 'https://github.com/vijayalaxmiduvva/mvnproject.git'
           }
         }
 }
 
